print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill?"))
tip_percentage = float(input("How much tip would you like to give? 10, 12, or 15?"))
amount_of_people = int(input("How many peoplle to split the bill?"))
tip_amount = float((total_bill * (tip_percentage / 100) + total_bill) / amount_of_people)
print(f"Each person should pay: $ {round(tip_amount, 2)}")